controller_manager:
  ros__parameters:
    update_rate: 600  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - right_j0
      - right_j1
      - right_j2
      - right_j3
      - right_j4
      - right_j5
      - right_j6
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      right_j0:
        goal: 0.05
      right_j1:
        goal: 0.05
      right_j2:
        goal: 0.05
      right_j3:
        goal: 0.05
      right_j4:
        goal: 0.05
      right_j5:
        goal: 0.05
      right_j6:
        goal: 0.05