/**:
  ros__parameters:
    robot_description_kinematics:
      right_arm:
        kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        kinematics_solver_search_resolution: 0.005
        kinematics_solver_timeout: 0.05
      head:
        kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        kinematics_solver_search_resolution: 0.005
        kinematics_solver_timeout: 0.05
    robot_description_planning:
      joint_limits:
        right_j0:
          has_position_limits: true
          max_position: !degrees  180.0
          min_position: !degrees -180.0
        right_j1:
          has_position_limits: true
          max_position: !degrees  180.0
          min_position: !degrees -180.0
        right_j2:
          has_position_limits: true
          max_position: !degrees  180.0
          min_position: !degrees -180.0
        right_j3:
          has_position_limits: true
          max_position: !degrees  180.0
          min_position: !degrees -180.0
        right_j4:
          has_position_limits: true
          max_position: !degrees  180.0
          min_position: !degrees -180.0
        right_j5:
          has_position_limits: true
          max_position: !degrees  180.0
          min_position: !degrees -180.0
        right_j6:
          has_position_limits: true
          max_position: !degrees  180.0
          min_position: !degrees -180.0
        head_pan:
          has_position_limits: true
          max_position: !degrees  180.0
          min_position: !degrees -180.0
        torso_t0:
          has_position_limits: false
        right_gripper_l_finger_joint:
          has_position_limits: false
        right_gripper_r_finger_joint:
          has_position_limits: false
